//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int ID_Basket { get; set; }
        public int ID_Order { get; set; }
        public int ID_Ticket { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
