//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaleTicket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Basket = new HashSet<Basket>();
        }
    
        public int ID_Ticket { get; set; }
        public string TicketPointOfDeparture { get; set; }
        public string TicketPointDestination { get; set; }
        public string TicketTransport { get; set; }
        public string TicketTypeOfTicket { get; set; }
        public int ID_PointOfDeparture { get; set; }
        public int ID_PointDestination { get; set; }
        public int ID_Transport { get; set; }
        public int ID_TypeOfTicket { get; set; }
        public System.DateTime Data { get; set; }
        public double Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Destination Destination1 { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual TypeOfTicket TypeOfTicket { get; set; }
    }
}
